<a href="https://colab.research.google.com/github/sjohn214/Colab_Predictive2026/blob/Lab-5/ISM645_Week5_Lab_SLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 5 Lab — Pandas Fundamentals

**ISM 645 · Principles of Predictive Analytics**

This lab practices everything from the Week 5 lecture: Series, DataFrames, the Index
object, explicit vs. implicit indexing, boolean selection, arithmetic and ufuncs,
missing data, sorting, and ranking.

There are **10 questions**. Each has several short parts. Work through them in order —
later questions reuse objects you build in earlier ones.

## Learning goals

By the end of this lab you should be able to:

- Create a `Series` from a list and from a dictionary, and describe its parts
- Build a `DataFrame` from a dictionary of lists and from a list of dictionaries
- Set, inspect, and reset the index
- Select data by **label** (`[]`, `.loc`) and by **position** (`.iloc`), and explain the difference
- Filter rows with boolean conditions
- Create new columns with arithmetic and NumPy universal functions
- Detect, drop, and fill missing values
- Sort by values and by index, and rank values

## How to work through this lab

1. Run the **Setup** cell first. Every question depends on it.
2. Replace each `...` with your own code. Do not delete the `print()` lines — they show your answer.
3. Some parts ask you to write a short answer in a markdown cell. Type directly in the cell provided.
4. Difficulty increases through the lab. The last parts of Questions 7–10 go beyond the
   minimum, and are there for anyone who wants to push further.

## How the notebook remembers things

The notebook has one memory, shared by every cell, and it only changes when you **run** a
cell. Editing a cell changes nothing until you run it. This causes three specific problems
in this lab, and all three look like "my code ignores my changes":

1. **You edited a cell but didn't run it.** Pressing Enter adds a line; **Shift + Enter**
   runs the cell. Check the `[ ]` to the left — a number means it has been run, and the
   number tells you the order cells ran in, which is not always top to bottom.
2. **You changed something upstream.** `orders_idx` (Question 3) and `sales` (Question 8)
   are built once from `orders`. Change `orders` afterwards and those two keep the *old*
   data until you re-run the cells that built them.
3. **You reused a variable name.** If Question 7(a) sets `mask` and a later part prints
   `orders.loc[mask]` without redefining it, you get part (a)'s answer every single time,
   no matter what you edit. Give each part its own name: `mask_b`, `mask_c`, and so on.

When output stops making sense, **Kernel → Restart & Run All** rebuilds everything from
scratch in order. That is the correct fix, not a workaround — but if you need it several
times per question, one of the three causes above is usually the real reason.

## Submitting

Run **Kernel → Restart & Run All** before you submit, so your notebook shows clean output
from top to bottom. Then upload the `.ipynb` file to Canvas.

---

## Setup — run this cell first

`orders` is a small table of campus bookstore purchases. Notice that `order_id` values
are **not** consecutive (1001, 1002, 1004, ...). That will matter a lot in Questions 5 and 6.

In [73]:
import pandas as pd
import numpy as np

orders = pd.DataFrame({
    'order_id': [1001, 1002, 1004, 1007, 1008, 1010, 1013, 1015],
    'item':     ['notebook', 'pen', 'stapler', 'notebook',
                 'backpack', 'pen', 'calculator', 'backpack'],
    'category': ['paper', 'writing', 'office', 'paper',
                 'bags', 'writing', 'electronics', 'bags'],
    'qty':      [3, 12, 2, 5, 1, 8, 2, 3],
    'price':    [3.99, 1.50, 5.25, 3.99, 24.99, 1.50, 12.75, 24.99]
})

orders

,order_id,item,category,qty,price
0,1001,notebook,paper,3,3.99
1,1002,pen,writing,12,1.50
2,1004,stapler,office,2,5.25
3,1007,notebook,paper,5,3.99
4,1008,backpack,bags,1,24.99
5,1010,pen,writing,8,1.50
6,1013,calculator,electronics,2,12.75
7,1015,backpack,bags,3,24.99


---

## Question 1 — Creating and accessing a Series

A Series is a one-dimensional labeled array. It has two parts: the **data** (the values)
and the **index** (a label for each value).

**(a)** Build a Series called `weekly_sales` from the `values` list below, using `days` as
the index and `'sales'` as the name.

**(b)** Build a Series called `prices` from the dictionary provided. Notice you don't pass
an index — pandas takes it from the dictionary keys.

**(c)** Print the `.values`, `.index`, `.name`, and `.dtype` of `weekly_sales`.

**(d)** Using **position**, print the first value, then the first three values.

**(e)** Using **labels**, print the value for `'Wed'`, then the values for `'Mon'` and
`'Fri'` together, then everything from `'Tue'` through `'Thu'`.

In [74]:
import numpy as np
import pandas as pd

# (a)
values = [120, 95, 143, 87, 160]
days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']
prices_dict = {'Mon': 10.5, 'Tue': 11.0, 'Wed': 10.75, 'Thu': 11.25, 'Fri': 12.0}

weekly_sales = pd.Series(data=np.array(values, dtype=np.int32), index=days, name='sales')
print(weekly_sales)
print()

Mon    120
Tue     95
Wed    143
Thu     87
Fri    160
Name: sales, dtype: int32



In [75]:
# (b)
price_dict = {'pen': 1.50, 'notebook': 3.99, 'stapler': 5.25}

prices = pd.Series(prices_dict)
print(prices)
print()

Mon    10.50
Tue    11.00
Wed    10.75
Thu    11.25
Fri    12.00
dtype: float64



In [76]:
# (c) the parts a Series is made of
print('values:', [weekly_sales.values])
print('index :', [weekly_sales.index.to_numpy()])
print('name  :', [weekly_sales.name])
print('dtype :', [weekly_sales.dtype])
print()

values: [array([120,  95, 143,  87, 160], dtype=int32)]
index : [array(['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], dtype=object)]
name  : ['sales']
dtype : [dtype('int32')]



In [77]:
# (d) access by POSITION
print(f"first value: {weekly_sales.iloc[0]}")   # the first value only
print(f"\nfirst three values")   # the first three values
print(weekly_sales.iloc[:3])
print()

first value: 120

first three values
Mon    120
Tue     95
Wed    143
Name: sales, dtype: int32



In [78]:
# (e) access by LABEL
print(f"value for 'Wed': {weekly_sales.loc['Wed']}")   # the value for 'Wed'
print("\nvalues for 'Mon' and 'Fri':")   # the values for 'Mon' and 'Fri'
print(weekly_sales.loc[['Mon', 'Fri']])
print("\nvales from 'Tue' through 'Thu':")   # everything from 'Tue' through 'Thu'
print(weekly_sales.loc['Tue':'Thu'])
print()

value for 'Wed': 143

values for 'Mon' and 'Fri':
Mon    120
Fri    160
Name: sales, dtype: int32

vales from 'Tue' through 'Thu':
Tue     95
Wed    143
Thu     87
Name: sales, dtype: int32



---

## Question 2 — Building and inspecting a DataFrame

The Setup cell built `orders` from a **dictionary of lists**. A DataFrame can also be built
from a **list of dictionaries**, where each dictionary is one row.

**(a)** Rebuild just the first three orders as `orders_alt`, using a list of dictionaries.
Include the columns `order_id`, `item`, `qty`, and `price`.

**(b)** Print the `.shape`, `.columns`, `.index`, and `.dtypes` of `orders`.

**(c)** Print the first 3 rows, then the last 2 rows.

**(d)** Answer the short question in the markdown cell that follows.

In [79]:
import pandas as pd
import numpy as np

orders = pd.DataFrame({
    'order_id': [1001, 1002, 1004, 1007, 1008, 1010, 1013, 1015],
    'item':     ['notebook', 'pen', 'stapler', 'notebook',
                 'backpack', 'pen', 'calculator', 'backpack'],
    'category': ['paper', 'writing', 'office', 'paper',
                 'bags', 'writing', 'electronics', 'bags'],
    'qty':      [3, 12, 2, 5, 1, 8, 2, 3],
    'price':    [3.99, 1.50, 5.25, 3.99, 24.99, 1.50, 12.75, 24.99]
})

# (a) same data, different construction style
orders_alt = pd.DataFrame([
    {'order_id': 1001, 'item': 'notebook', 'qty': 3, 'price': 3.99},
    {'order_id': 1002, 'item': 'pen', 'qty': 12, 'price': 1.50},
    {'order_id': 1004, 'item': 'stapler', 'qty': 2, 'price': 5.25}
])
print(orders_alt)

   order_id      item  qty  price
0      1001  notebook    3   3.99
1      1002       pen   12   1.50
2      1004   stapler    2   5.25


In [80]:
# (b) what is this table made of?
print('shape  :', orders.shape)
print('columns:', orders.columns)
print('index  :', orders.index)
print('dtypes :')
print(orders.dtypes)
print()

shape  : (8, 5)
columns: Index(['order_id', 'item', 'category', 'qty', 'price'], dtype='object')
index  : RangeIndex(start=0, stop=8, step=1)
dtypes :
order_id      int64
item         object
category     object
qty           int64
price       float64
dtype: object



In [81]:
# (c)
print(orders.head(3))   # first 3 rows
print(orders.tail(2))   # last 2 rows
print()

   order_id      item category  qty  price
0      1001  notebook    paper    3   3.99
1      1002       pen  writing   12   1.50
2      1004   stapler   office    2   5.25
   order_id        item     category  qty  price
6      1013  calculator  electronics    2  12.75
7      1015    backpack         bags    3  24.99



**(d) Your answer:** How many rows and columns does `orders` have? Name the three
structural components of a DataFrame from the lecture, and say which one `qty` is.

*(8,5) eight rows and five columns
Index = the row labels
Columns = the column lables
Data/Values = the data grid/numpy array inside
Qty is a column label that forms a pandas series*

---

## Question 3 — The Index object

The index labels the rows. It is what makes label-based lookup fast.

> **Run part (a) before you go on.** Questions 4, 5, 6, and 10 all use `orders_idx`.

**(a)** Make `order_id` the index of `orders` and store the result as `orders_idx`. Show the
first few rows.

**(b)** Print `orders_idx.index`, the index's `.name`, and whether the index is unique.

**(c)** Print the index of the original `orders`. How is it different from the index of
`orders_idx`?

**(d)** Turn the index back into a regular column with `reset_index()`, storing the result
as `orders_reset`. Show the first 3 rows and print the new index.

In [82]:
# (a)
orders_idx = orders.set_index('order_id')
orders_idx.head()

,item,category,qty,price
order_id,,,,
1001,notebook,paper,3,3.99
1002,pen,writing,12,1.50
1004,stapler,office,2,5.25
1007,notebook,paper,5,3.99
1008,backpack,bags,1,24.99


In [83]:
# (b)
print('index    :', orders_idx.index)
print('name     :', orders_idx.index.name)
print('is unique:', orders_idx.index.is_unique)
print()

index    : Index([1001, 1002, 1004, 1007, 1008, 1010, 1013, 1015], dtype='int64', name='order_id')
name     : order_id
is unique: True



In [84]:
# (c) compare with the index of the original table
print('original index', orders.index)
print()

original index RangeIndex(start=0, stop=8, step=1)



In [85]:
# (d)
orders_reset = orders_idx.reset_index()
print(orders_reset.head(3)) #show first 3 rows
print('index after reset:', orders_reset.index)
print()

   order_id      item category  qty  price
0      1001  notebook    paper    3   3.99
1      1002       pen  writing   12   1.50
2      1004   stapler   office    2   5.25
index after reset: RangeIndex(start=0, stop=8, step=1)



---

## Question 4 — Explicit indexing: dictionary-style and attribute-style

Both of these are *explicit* indexing, because both use the actual column **name**.

> **Needs:** `orders_idx` from Question 3(a).

**(a)** Select the `item` column using dictionary-style indexing (square brackets). Show
the first 3 values.

**(b)** Select the same column using attribute-style indexing (dot notation).

**(c)** Select `item` and `price` together. Then print the `type()` of `orders_idx['item']`
and of `orders_idx[['item']]`. They are not the same — note what each one is.

**(d)** The lecture listed two rules for attribute-style indexing. Run the cell below to
build a small DataFrame that breaks both rules, then answer the question underneath.

In [86]:
# (a) dictionary-style
orders_idx = orders.set_index('order_id')
orders_idx.head()
print(orders_idx.head(3))

              item category  qty  price
order_id                               
1001      notebook    paper    3   3.99
1002           pen  writing   12   1.50
1004       stapler   office    2   5.25


In [87]:
# (b) attribute-
orders_idx = orders.set_index('order_id')
print(orders_idx.item.head(3))
print()

order_id
1001    notebook
1002         pen
1004     stapler
Name: item, dtype: object



In [88]:
# (c) one column vs. a list of columns
print(orders_idx[['item', 'price']])    # 'item' and 'price' together, first 3 rows
print(type(orders_idx['item']))
print(type(orders_idx[['item']]))
print()

                item  price
order_id                   
1001        notebook   3.99
1002             pen   1.50
1004         stapler   5.25
1007        notebook   3.99
1008        backpack  24.99
1010             pen   1.50
1013      calculator  12.75
1015        backpack  24.99
<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>



In [89]:
# (d) two columns that break the rules for attribute-style access
tricky = pd.DataFrame({'unit price': [1.50, 3.99],
                       'product': ['pen', 'notebook']})
print(tricky)

# Bracket-style works for both:
print(tricky['unit price'])
print(tricky['product'])

# Now look at what attribute-style gives you for 'product':
print(type(tricky.product))

   unit price   product
0        1.50       pen
1        3.99  notebook
0    1.50
1    3.99
Name: unit price, dtype: float64
0         pen
1    notebook
Name: product, dtype: object
<class 'method'>


**(d) Your answer:** `tricky.unit price` is not even valid Python — why not? And
`tricky.product` runs without error but does **not** give you the column. What does it give
you instead, and why?

*Python variable and attribute names can't contain spaces and it won't provide the column data because we used parenthesis instead of brackets. What was returned was a pandas built-in method/function. This happened because there is a built-in mathematical method named .product() and we were in fact looking for a 'product.'*

---

## Question 5 — Label-based selection with `.loc`

`.loc` selects by **label**. Remember the order IDs are 1001, 1002, 1004, 1007, 1008, 1010,
1013, 1015 — with gaps.

> **Needs:** `orders_idx` from Question 3(a).

**(a)** Select the single row with order ID 1004.

**(b)** Select the rows with order IDs 1001 and 1008.

**(c)** Select the slice from 1002 to 1008. Count the rows you get back — is the end label
included?

**(d)** Select just the `item` value for order 1007 (one value, not a row).

**(e)** Select rows 1002 through 1007, showing only the `item` and `price` columns.

In [90]:
orders_idx = orders.set_index('order_id')
# (a) one row by label
row_1004 = orders_idx.loc[1004]
print("(a):\n", row_1004, "\n")
print()

(a):
 item        stapler
category     office
qty               2
price          5.25
Name: 1004, dtype: object 




In [91]:
# (b) two specific rows by label
rows_list = orders_idx.loc[[1001, 1008]]
print("(b):\n", rows_list, "\n")
print()

(b):
               item category  qty  price
order_id                               
1001      notebook    paper    3   3.99
1008      backpack     bags    1  24.99 




In [92]:
# (c) a slice of labels
row_slice = orders_idx.loc[1002:1008]
print("(c):\n", row_slice, "\n")

result = row_slice
print(result)
print('rows returned:', len(result))
print()

(c):
               item category  qty  price
order_id                               
1002           pen  writing   12   1.50
1004       stapler   office    2   5.25
1007      notebook    paper    5   3.99
1008      backpack     bags    1  24.99 

              item category  qty  price
order_id                               
1002           pen  writing   12   1.50
1004       stapler   office    2   5.25
1007      notebook    paper    5   3.99
1008      backpack     bags    1  24.99
rows returned: 4



In [93]:
# (d) a single value: row label + column label
item_1007 = orders_idx.loc[1007, 'item']
print("(d):", item_1007, "\n")
print()

(d): notebook 




In [94]:
# (e) a slice of rows and a list of columns
subset = orders_idx.loc[1002:1007, ['item', 'price']]
print("(e):\n", subset)
print()

(e):
               item  price
order_id                 
1002           pen   1.50
1004       stapler   5.25
1007      notebook   3.99



---

## Question 6 — Position-based selection with `.iloc`

`.iloc` ignores labels entirely and counts positions from 0.

> **Needs:** `orders_idx` from Question 3(a).

**(a)** Select the row in the first position.

**(b)** Select the first three rows.

**(c)** Select the rows in positions 0, 2, and 4.

**(d)** Select the first 3 rows and the first 2 columns.

**(e)** Select the last two rows.

**(f)** Run the comparison cell, then answer the question below it.

In [95]:
orders_idx = orders.set_index('order_id')
# (a)
first_row = orders_idx.iloc[0]
print("(a):\n", first_row, "\n")
print()

(a):
 item        notebook
category       paper
qty                3
price           3.99
Name: 1001, dtype: object 




In [96]:
# (b)
first_three_rows = orders_idx.iloc[0:3]
print("(b):\n", first_three_rows, "\n")
print()

(b):
               item category  qty  price
order_id                               
1001      notebook    paper    3   3.99
1002           pen  writing   12   1.50
1004       stapler   office    2   5.25 




In [97]:
# (c) non-contiguous positions
specific_rows = orders_idx.iloc[[0, 2, 4]]
print("(c):\n", specific_rows, "\n")
print()

(c):
               item category  qty  price
order_id                               
1001      notebook    paper    3   3.99
1004       stapler   office    2   5.25
1008      backpack     bags    1  24.99 




In [98]:
# (d) rows and columns by position
rows_and_cols = orders_idx.iloc[0:3, 0:2]
print("(d):\n", rows_and_cols, "\n")
print()

(d):
               item category
order_id                   
1001      notebook    paper
1002           pen  writing
1004       stapler   office 




In [99]:
# (e) the last two rows
last_two_rows = orders_idx.iloc[-2:]
print("(e):\n", last_two_rows)
print()

(e):
                 item     category  qty  price
order_id                                     
1013      calculator  electronics    2  12.75
1015        backpack         bags    3  24.99



In [100]:
# (f) the key difference, side by side
print('loc[1002:1008] returns', len(orders_idx.loc[1002:1008]), 'rows')
print('iloc[1:4]      returns', len(orders_idx.iloc[1:4]), 'rows')

loc[1002:1008] returns 4 rows
iloc[1:4]      returns 3 rows


**(f) Your answer:** Both selections start at the second row of the table, but they return
different numbers of rows. Explain why.

*One uses .loc and the other uses .iloc. .loc includes and endpoint and .iloc excludes the endpoint. They follow different slicing rules in Python. In a side by side comparison the slicing for .loc is label-based, inclusive, and retrieves four rows. iloc is integer-positioned, exclusive, and retrieves three rows.*

---

## Question 7 — Boolean (conditional) selection

A comparison on a column produces a Series of `True`/`False`, and you can use that to pick
rows. Use the original `orders` table for this question.

**(a)** Print the boolean mask for `qty >= 5` on its own, so you can see what pandas is
actually working with. Then use it to select those rows.

**(b)** Select rows where `price` is above 3 **and** `qty` is at least 3.

**(c)** Select rows where the category is `bags` **or** `electronics`.

**(d)** Do the same as (c), but with `.isin()` instead of `|`.

**(e)** Select rows where the item is a pen or a notebook **and** the quantity is more than
4, returning only the `order_id`, `item`, and `qty` columns.

In [101]:
import pandas as pd
import numpy as np

orders = pd.DataFrame({
    'order_id': [1001, 1002, 1004, 1007, 1008, 1010, 1013, 1015],
    'item':     ['notebook', 'pen', 'stapler', 'notebook',
                 'backpack', 'pen', 'calculator', 'backpack'],
    'category': ['paper', 'writing', 'office', 'paper',
                 'bags', 'writing', 'electronics', 'bags'],
    'qty':      [3, 12, 2, 5, 1, 8, 2, 3],
    'price':    [3.99, 1.50, 5.25, 3.99, 24.99, 1.50, 12.75, 24.99]
})
# (a) the mask itself, then the rows it selects
# Later parts: give each mask its own name (mask_b, mask_c, ...) so that an old
# mask can never linger and hand you the previous part's answer.
mask_a = orders['qty'] >= 5
print("(a) Mask:\n", mask_a)
print("\n(a) selected rows:\n", orders[mask_a], "\n" + "="*40)
print()

(a) Mask:
 0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
Name: qty, dtype: bool

(a) selected rows:
    order_id      item category  qty  price
1      1002       pen  writing   12   1.50
3      1007  notebook    paper    5   3.99
5      1010       pen  writing    8   1.50 



In [102]:
# (b) two conditions with AND -- wrap each condition in its own parentheses
mask_b = (orders['price'] > 3) & (orders['qty'] >= 3)
print("(b):\n", orders[mask_b], "\n" + "="*40)
print()

(b):
    order_id      item category  qty  price
0      1001  notebook    paper    3   3.99
3      1007  notebook    paper    5   3.99
7      1015  backpack     bags    3  24.99 



In [103]:
# (c) two conditions with OR
mask_c = (orders['category'] == 'bags') | (orders['category'] == 'electronics')
print("(c):\n", orders[mask_c], "\n" + "="*40)
print()

(c):
    order_id        item     category  qty  price
4      1008    backpack         bags    1  24.99
6      1013  calculator  electronics    2  12.75
7      1015    backpack         bags    3  24.99 



In [104]:
# (d) the same result using .isin()
mask_d = orders['category'].isin(['bags', 'electronics'])
print("(d):\n", orders[mask_d], "\n" + "="*40)
print()

(d):
    order_id        item     category  qty  price
4      1008    backpack         bags    1  24.99
6      1013  calculator  electronics    2  12.75
7      1015    backpack         bags    3  24.99 



In [105]:
# (e) combine .isin() with a numeric condition, and pick columns too
mask_e = orders['item'].isin(['pen', 'notebook']) & (orders['qty'] > 4)
columns_e = ['order_id', 'item', 'qty']
print("(e):\n", orders.loc[mask_e, columns_e])
print()

(e):
    order_id      item  qty
1      1002       pen   12
3      1007  notebook    5
5      1010       pen    8



---

## Question 8 — Arithmetic and NumPy universal functions

Operations apply to a whole column at once — no loops needed. Work on a **copy** so you
don't disturb the original table.

**(a)** Add a `total` column equal to `qty * price`.

**(b)** Add `total_with_tax`: the total plus 7% sales tax, rounded to 2 decimals with
`np.round()`.

**(c)** Add `log_total` using `np.log1p()` on the total.

**(d)** Add `ships_free`: the string `'yes'` when total is 20 or more, `'no'` otherwise. Use
`np.where()`.

**(e)** Print the mean, max, and sum of the `total` column.

In [106]:
# work on a copy of the original table
# WARNING: re-running this cell rebuilds `sales` from scratch and discards every
# column added below it, including the rank columns from Question 10. If you come
# back to this cell later, finish with Kernel -> Restart & Run All.
sales = orders.copy()

# (a)
sales['total'] = sales['qty'] * sales['price']
print(sales)
print()

   order_id        item     category  qty  price  total
0      1001    notebook        paper    3   3.99  11.97
1      1002         pen      writing   12   1.50  18.00
2      1004     stapler       office    2   5.25  10.50
3      1007    notebook        paper    5   3.99  19.95
4      1008    backpack         bags    1  24.99  24.99
5      1010         pen      writing    8   1.50  12.00
6      1013  calculator  electronics    2  12.75  25.50
7      1015    backpack         bags    3  24.99  74.97



In [107]:
# (b) 7% tax, rounded to 2 decimals
sales['total_with_tax'] = (sales['total'] * 0.07).round(2)
print(sales[['item', 'total', 'total_with_tax']])
print()

         item  total  total_with_tax
0    notebook  11.97            0.84
1         pen  18.00            1.26
2     stapler  10.50            0.74
3    notebook  19.95            1.40
4    backpack  24.99            1.75
5         pen  12.00            0.84
6  calculator  25.50            1.78
7    backpack  74.97            5.25



In [108]:
# (c) a NumPy ufunc applied to a whole column
sales['log_total'] = np.log1p(sales['total'])
print(sales[['total', 'log_total']])
print()

   total  log_total
0  11.97   2.562639
1  18.00   2.944439
2  10.50   2.442347
3  19.95   3.042139
4  24.99   3.257712
5  12.00   2.564949
6  25.50   3.277145
7  74.97   4.330339



In [109]:
# (d) conditional column with np.where
sales['ships_free'] = np.where(sales['total'] >= 20, 'yes', 'no')
print(sales[['item', 'total', 'ships_free']])
print()

         item  total ships_free
0    notebook  11.97         no
1         pen  18.00         no
2     stapler  10.50         no
3    notebook  19.95         no
4    backpack  24.99        yes
5         pen  12.00         no
6  calculator  25.50        yes
7    backpack  74.97        yes



In [110]:
# (e) summary statistics
print('mean:', sales['total'].mean())
print('max :', sales['total'].max())
print('sum :', sales['total'].sum())
print()

mean: 24.735
max : 74.97
sum : 197.88



---

## Question 9 — Missing data

Run the cell below to create a small table of product returns with missing values in it.

**(a)** Show the full `True`/`False` grid of missing values, then the count of missing values
per column, then the total number of missing values in the table.

**(b)** Drop only the rows where **every** value is missing.

**(c)** Drop rows that are missing a value in `days_to_return` **or** `refund`, leaving
`reason` alone.

**(d)** Drop *columns* that contain any missing value. Look carefully at the result, then
answer the question below.

**(e)** On a copy called `filled`, fill the gaps three different ways: `days_to_return` with
the column mean, `reason` by carrying the previous value forward, and `refund` by carrying
the next value backward.

**(f)** Answer the short question about `NaN` and `None`.

In [111]:
returns = pd.DataFrame({
    'days_to_return': [5.0, np.nan, 12.0, np.nan, 8.0],
    'reason': ['damaged', 'wrong item', None, None, 'too small'],
    'refund': [11.97, 18.00, np.nan, np.nan, 24.99]
})
returns

,days_to_return,reason,refund
0,5.0,damaged,11.97
1,NaN,wrong item,18.00
2,12.0,None,NaN
3,NaN,None,NaN
4,8.0,too small,24.99


In [112]:
import pandas as pd
import numpy as np

returns = pd.DataFrame({
    'days_to_return': [5.0, np.nan, 12.0, np.nan, 8.0],
    'reason': ['damaged', 'wrong item', None, None, 'too small'],
    'refund': [11.97, 18.00, np.nan, np.nan, 24.99]
})

# (a) where are the gaps?
print(returns.isna)           # the full True/False grid
print(returns.isna().sum())           # count per column
print('total missing:', returns.isna().sum().sum())

<bound method DataFrame.isna of    days_to_return      reason  refund
0             5.0     damaged   11.97
1             NaN  wrong item   18.00
2            12.0        None     NaN
3             NaN        None     NaN
4             8.0   too small   24.99>
days_to_return    2
reason            2
refund            2
dtype: int64
total missing: 6


In [113]:
# (b) drop rows only if the entire row is missing
clean_returns =returns.dropna(how='all')
print(clean_returns)
print()

   days_to_return      reason  refund
0             5.0     damaged   11.97
1             NaN  wrong item   18.00
2            12.0        None     NaN
4             8.0   too small   24.99



In [114]:
# (c) drop rows missing a value in specific columns
clean_subset = returns.dropna(subset=['days_to_return', 'refund'], how='any')
print(clean_subset)
print()

   days_to_return     reason  refund
0             5.0    damaged   11.97
4             8.0  too small   24.99



In [115]:
# (d) drop columns containing any missing value
clean_columns = returns.dropna(axis=1)
print(clean_columns)
print()

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]



**(d) Your answer:** What did you get back, and why did that happen with this particular
table? When would dropping columns be a reasonable choice?

*Every column contains at least one missing value and because pandas defaults by dropping columns missing any data, all three were removed. This left an empty structure with just the original row index behind.*

In [116]:
import pandas as pd
import numpy as np

returns = pd.DataFrame({
    'days_to_return': [5.0, np.nan, 12.0, np.nan, 8.0],
    'reason': ['damaged', 'wrong item', None, None, 'too small'],
    'refund': [11.97, 18.00, np.nan, np.nan, 24.99]
})


# (e) three different filling strategies
filled = returns.copy()
filled['days_to_return'] = filled['days_to_return'].fillna(filled['days_to_return'].mean())
filled['reason'] = filled['reason'].ffill()
filled['refund'] = filled['refund'].bfill()
print(filled)
print()

   days_to_return      reason  refund
0        5.000000     damaged   11.97
1        8.333333  wrong item   18.00
2       12.000000  wrong item   24.99
3        8.333333  wrong item   24.99
4        8.000000   too small   24.99



In [117]:
# use None into the reason column but np.nan into the numeric columns.
import pandas as pd
import numpy as np

# Recreating the table using explicit None and np.nan types
returns = pd.DataFrame({
    'days_to_return': [5.0, np.nan, 12.0, np.nan, 8.0],
    'reason': ['damaged', 'wrong item', None, None, 'too small'],
    'refund': [11.97, 18.00, np.nan, np.nan, 24.99]
})

print(returns.isna())
print()

   days_to_return  reason  refund
0           False   False   False
1            True   False   False
2           False    True    True
3            True    True    True
4           False   False   False



**(f) Your answer:** You typed `None` into the `reason` column but `np.nan` into the numeric
columns. Print `returns.isna()` again and note that pandas flags both as missing. From the
lecture, what is the difference between `NaN` and `None`?

*Pandas flags both the np.nan values in rows 1 & 3 and the None values in rows 2 & 3 as true for their missing values. The difference between them None will throw a TypeError because it breaks traditional math operations whereas NaN propagate through math and will convert for the missing numeric or computational values.*

---

## Question 10 — Sorting and ranking

Use the `sales` table you built in Question 8.

> **Needs:** `sales` from Question 8 and `orders_idx` from Question 3(a). If a cell here
> raises `KeyError: 'total'`, the Question 8(a) cell has been re-run since — do
> **Kernel → Restart & Run All**.

**(a)** Sort by `total`, largest first.

**(b)** Sort by `category` A–Z, and within each category by `total` largest first.

**(c)** Sort `orders_idx` by its index, largest order ID first.

**(d)** Add a `price_rank` column ranking `price` from smallest to largest with the default
`method='average'`. Sort by price so you can see the ranks in order, then answer the
question below.

**(e)** Add `total_rank` that ranks `total` from **largest to smallest** using
`method='min'`, then show the three biggest orders.

In [118]:
sales = orders.copy()
sales['total'] = sales['qty'] * sales['price']

# (a)
sales_sorted = sales.sort_values(by='total', ascending=False)
print(sales_sorted[['item', 'qty', 'price', 'total']])
print()

         item  qty  price  total
7    backpack    3  24.99  74.97
6  calculator    2  12.75  25.50
4    backpack    1  24.99  24.99
3    notebook    5   3.99  19.95
1         pen   12   1.50  18.00
5         pen    8   1.50  12.00
0    notebook    3   3.99  11.97
2     stapler    2   5.25  10.50



In [119]:
# (b) two sort keys, two different directions
sales_sorted = sales.sort_values(by=['category', 'total'], ascending=[True, False])
print(sales_sorted[['category', 'item', 'total']])
print()

      category        item  total
7         bags    backpack  74.97
4         bags    backpack  24.99
6  electronics  calculator  25.50
2       office     stapler  10.50
3        paper    notebook  19.95
0        paper    notebook  11.97
1      writing         pen  18.00
5      writing         pen  12.00



In [120]:
# (c) sort by the index instead of by a column
orders_sorted_idx = orders_idx.sort_index(ascending=False)
print("(c):\n", orders_sorted_idx, "\n" + "="*40)
print()

(c):
                 item     category  qty  price
order_id                                     
1015        backpack         bags    3  24.99
1013      calculator  electronics    2  12.75
1010             pen      writing    8   1.50
1008        backpack         bags    1  24.99
1007        notebook        paper    5   3.99
1004         stapler       office    2   5.25
1002             pen      writing   12   1.50
1001        notebook        paper    3   3.99 



In [121]:
# (d) ranking with the default tie handling
sales['price_rank'] = sales['price'].rank(method='average', ascending=True)
sales_sorted_price = sales.sort_values(by='price')
print(sales[['item', 'price', 'price_rank']].sort_values('price'))
print()

         item  price  price_rank
1         pen   1.50         1.5
5         pen   1.50         1.5
3    notebook   3.99         3.5
0    notebook   3.99         3.5
2     stapler   5.25         5.0
6  calculator  12.75         6.0
4    backpack  24.99         7.5
7    backpack  24.99         7.5



**(d) Your answer:** Several ranks come out as `1.5`, `3.5`, and `7.5` rather than whole
numbers. Explain what produced the halves.

*When two or more values are identical, we handle ties using the method='average' that takes the ranking positions of those items and assigns them the average of those ranks to all tied items. In our case, halves were assigned.*

In [122]:
# (e) rank in the other direction, and break ties differently
sales['total_rank'] = sales['total'].rank(method='min', ascending=False)
three_biggest_orders = sales.sort_values(by='total', ascending=False).head(3)
print("(e):\n", three_biggest_orders[['item', 'total', 'total_rank']])
print()   # the three largest orders

(e):
          item  total  total_rank
7    backpack  74.97         1.0
6  calculator  25.50         2.0
4    backpack  24.99         3.0



---

## Before you submit

- [ ] Every `...` has been replaced with working code
- [ ] Every "Your answer" markdown cell has a written response
- [ ] **Kernel → Restart & Run All** completes with no errors, top to bottom, in order
- [ ] The `.ipynb` file is uploaded to Canvas